---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml
driver:
  name: podman
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:20.04}
    pre_build_image: true
    privileged: true
    override_command: false
    systemd: true
    tty: true
    published_ports:
      - 0.0.0.0:8080:80
      - 0.0.0.0:8443:443
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
verifier:
  name: ansible
